---
fullname: coq-show
shortname: coq-show
opam_name: coq-show
namespace: Show

organization: liyishuai
community: false
coqdoc: false
plugin: false

license:
  fullname: BSD 3-Clause "New" or "Revised" License
  identifier: BSD-3-Clause

synopsis: The Show class in Coq
description: A clone of the Show class in Haskell.

authors:
  - name: Leonidas Lampropoulos
    initial: true
  - name: Maxime Dénès
    initial: true
  - name: Cătălin Hrițcu
    initial: true
  - name: Benjamin C. Pierce
    initial: true
  - name: Li-yao Xia
  - name: Yishuai Li

maintainers:
  - name: Leonidas Lampropoulos
    nickname: lemonidas
  - name: Yishuai Li
    nickname: liyishuai
  - name: Li-yao Xia
    nickname: Lysxia

opam-file-maintainer: Yishuai Li <yishuai@upenn.edu>
opam-file-version: dev

travis: true
action: true
circleci: true

supported_coq_versions:
  text: 8.10 or later
  opam: '{ >= "8.10" }'

tested_coq_opam_versions:
  - version: '8.10'
  - version: '8.11'
  - version: 'dev'
